#pragma once
#include "iostream"

std::string book_ () {
        std::string book = "\"David and Emma gazed at each other across the table. The young couple were content: the meal was delicious, the candlelight was soft and the music captured the moment perfectly. \\n\"\n"
        "                        \"\\n\"\n"
        "                        \"David looked at Emma's beautiful smile. All the pain of his last break-up, all his doubts and fears about love melted away. His hand reached out and touched hers nervously. \\n\"\n"
        "                        \"\\n\"\n"
        "                        \"'I have something I want to ask you.' David searched her eyes to see if she guessed what was coming. \\n\"\n"
        "                        \"\\n\"\n"
        "                        \"Her smile was reassuring. She squeezed his hand. 'You needn't worry. Whatever it is, I'm sure I'll say yes!' \\n\"\n"
        "                        \"\\n\"\n"
        "                        \"A huge wave of excitement went through him as he prepared to ask the most important question of his life.\\n\"\n"
        "                        \"\\n\"\n"
        "                        \"From the corner of the restaurant, a strange man watched them. He sat, stiff and unmoving, at his table, pretending to read a menu. But all the while, he stared with cold eyes at the young couple. \\n\"\n"
        "                        \"\\n\"\n"
        "                        \"Back at their table, David suddenly felt his nerves return. \\n\"\n"
        "                        \"\\n\"\n"
        "                        \"'Excuse me,' he said to Emma. He pushed his chair back and went to the toilet. As he looked at his reflection in the mirror, he took a deep breath and told himself: 'Come on, David, come on! You can do this, mate! She's crazy about you!'\\n\"\n"
        "                        \"\\n\"\n"
        "                        \"He nodded at himself and, feeling braver, he stepped outside the bathroom. He bumped straight into the extremely tall man, who was waiting by the door. The man's eyes were a cold, bright blue and his face was pale with a sharp, pointed nose and thin, pale lips. \\n\"\n"
        "                        \"\\n\"\n"
        "                        \"'Oh, sorry!' said David. \\n\"\n"
        "                        \"\\n\"\n"
        "                        \"'Which one?' the man hissed. He spoke with a strange, heavy accent that David had never heard before.\\n\"\n"
        "                        \"\\n\"\n"
        "                        \"For a moment, David was confused until he realised what the other man meant. \\n\"\n"
        "                        \"\\n\"\n"
        "                        \"'Er ... oh! This one!' said David, helpfully. 'This is the men's toilet!'\\n\"\n"
        "                        \"\\n\"\n"
        "                        \"David went back into the restaurant, reaching into his pocket for the small, square-shaped box. He was now filled with courage. He was going to ask her.\\n\"\n"
        "                        \"\\n\"\n"
        "                        \"The taxi ride home was heaven. The happy pair discussed their future life together and shared sweet words of admiration. \\n\"\n"
        "                        \"\\n\"\n"
        "                        \"'The night I proposed!' said David. \\n\"\n"
        "                        \"\\n\"\n"
        "                        \"'The night I accepted!' replied Emma. \\n\"\n"
        "                        \"\\n\"\n"
        "                        \"'Just think, a whole life together!' \\n\"\n"
        "                        \"\\n\"\n"
        "                        \"'Caring, sharing, …' he began.\\n\"\n"
        "                        \"\\n\"\n"
        "                        \"'... loving, giving!' Emma finished his sentence.\\n\"\n"
        "                        \"\\n\"\n"
        "                        \"They smiled at each other in love and excitement. \\n\"\n"
        "                        \"\\n\"\n"
        "                        \"'You are so wonderful!' sighed David.\\n\"\n"
        "                        \"\\n\"\n"
        "                        \"'And you're absolutely gorgeous!' said Emma. 'I've never met anyone so lovely and kind! I'm so happy I could sing!' \\n\"\n"
        "                        \"\\n\"\n"
        "                        \"But as they entered their block of flats, holding hands, a tall figure watched them from the shadows. \\n\"\n"
        "                        \"\\n\"\n"
        "                        \"'Which one?' he whispered to himself. \\n\"\n"
        "                        \"\\n\"\n"
        "                        \"He watched the building, waiting for a light to come on and give away which flat was theirs. One minute went by … two … there it was! The light went on in a third-floor window. Emma was briefly visible as she closed the curtains. \\n\"\n"
        "                        \"\\n\"\n"
        "                        \"How often had the sharp-toothed watcher stood on corners like this observing his victims? Many corners! Many windows! A thin smile spread across his pale lips. He moved out of the shadows to the door and pressed all the doorbells. The vampire was always grateful for these modern flats. Sooner or later someone would let you in, thinking it was a pizza delivery. Silly humans! It was a kind of invitation – and that was all he needed to enter a home. \\n\"\n"
        "                        \"\\n\"\n"
        "                        \"As he climbed the stairs to the third floor and walked soundlessly down the hall, he could hear the young couple's laughter and conversation. As he pressed his ear against the door, he could hear their conversation. Young love made for the sweetest blood; it was so full of life and energy.\\n\"\n"
        "                        \"\\n\"\n"
        "                        \"'I feel as if I'm in a film,' she was saying.  \\n\"\n"
        "                        \"\\n\"\n"
        "                        \"'More like a dream,' he replied.\\n\"\n"
        "                        \"\\n\"\n"
        "                        \"'Yes, a dream. How lucky we are!' \\n\"\n"
        "                        \"\\n\"\n"
        "                        \"'Guess who I'll be dreaming about tonight!' he teased.\\n\"\n"
        "                        \"\\n\"\n"
        "                        \"'Who? Who?' \\n\"\n"
        "                        \"\\n\"\n"
        "                        \"'Her hair smells of roses! She's like an angel!'\\n\"\n"
        "                        \"\\n\"\n"
        "                        \"Their dream was about to become a nightmare, the vampire thought. He burst through the door and stood there with a cruel expression, showing his sharp teeth. The couple screamed and held each other in terrified silence. The vampire smelled the tension and tasted the fear. This was how he liked it. Fear made the blood even sweeter.\\n\"\n"
        "                        \"\\n\"\n"
        "                        \"'There's my wallet! On the table, there! Take it!' said David. 'Take anything you want!'\\n\"\n"
        "                        \"\\n\"\n"
        "                        \"'Indeed, I will take anything I want!' the vampire replied. \\n\"\n"
        "                        \"\\n\"\n"
        "                        \"'Fine! Fine! We won't stop you, I promise!' David cried.\\n\"\n"
        "                        \"\\n\"\n"
        "                        \"'You won't! I promise!' replied the vampire.\\n\"\n"
        "                        \"\\n\"\n"
        "                        \"As the light shone on the sharp, pointed teeth, the terrible realisation came to David and Emma at the same time. \\n\"\n"
        "                        \"\\n\"\n"
        "                        \"'Look at his teeth! Is he ... ?'\\n\"\n"
        "                        \"\\n\"\n"
        "                        \"'A vampire!!'\\n\"\n"
        "                        \"\\n\"\n"
        "                        \"'Which one?' the vampire hissed. 'It can be … only one!'\\n\"\n"
        "                        \"\\n\"\n"
        "                        \"The couple's eyes were wide open and staring. Their mouths hung open in horror. They held each other's hands and their stomachs filled with fear. \\n\"\n"
        "                        \"\\n\"\n"
        "                        \"'Already tonight,' continued the vampire. 'I have drunk from three. One more ... then … I can … sleep … and feel young again.'\\n\"\n"
        "                        \"\\n\"\n"
        "                        \"David felt a strong instinct as the vampire moved towards them. He stepped in front of Emma and protected his wife-to-be. Emma gratefully held on to his back. \\n\"\n"
        "                        \"\\n\"\n"
        "                        \"The vampire was in no rush. Who best to attack? he asked himself. Which one? \\n\"\n"
        "                        \"\\n\"\n"
        "                        \"'Thank you,' Emma whispered to David, 'for what you're doing for me.'\\n\"\n"
        "                        \"\\n\"\n"
        "                        \"'Of course, darling. I'm here to protect you.' Pride swept over him as he said the words. He could fight this vampire. All he needed was a cross, or something to stab him through the heart. He looked around for something ...\\n\"\n"
        "                        \"\\n\"\n"
        "                        \"'You're so selfless to offer yourself so bravely,' continued Emma, admiringly. \\n\"\n"
        "                        \"\\n\"\n"
        "                        \"'Pardon?' asked David. 'What the hell are you talking about?'\\n\"\n"
        "                        \"\\n\"\n"
        "                        \"'Oh!' said Emma. 'I just thought that with your love for me and everything …'\\n\"\n"
        "                        \"\\n\"\n"
        "                        \"David and the vampire stared at each other.\\n\"\n"
        "                        \"\\n\"\n"
        "                        \"'Now, listen, Emma. There is no doubt about my love for you!'\\n\"\n"
        "                        \"\\n\"\n"
        "                        \"'Really?' she replied, her voice heavy with disbelief. \\n\"\n"
        "                        \"\\n\"\n"
        "                        \"'But you can't expect me to just throw away my life!'\\n\"\n"
        "                        \"\\n\"\n"
        "                        \"'I wasn't saying you should!' she said. 'It's just one of our options, that's all!'\\n\"\n"
        "                        \"\\n\"\n"
        "                        \"'Well, think of another one!' he argued. 'Why don't you offer yourself up for me!'\\n\"\n"
        "                        \"\\n\"\n"
        "                        \"The mood in the room had certainly turned ugly. The vampire was displeased that the fear and love had turned into petty arguments.\\n\"\n"
        "                        \"\\n\"\n"
        "                        \"Emma was furious. 'I hope you're joking!'\\n\"\n"
        "                        \"\\n\"\n"
        "                        \"'Let's see how strong your love is!' he said, angrily.\\n\"\n"
        "                        \"\\n\"\n"
        "                        \"'What a gentleman!' \\n\"\n"
        "                        \"\\n\"\n"
        "                        \"'What a lovely woman I was planning to marry. Offering me up like a bone to a dog!'\\n\"\n"
        "                        \"\\n\"\n"
        "                        \"'You said my hair smells of roses!' she cried. \\n\"\n"
        "                        \"\\n\"\n"
        "                        \"'All right, all right! Calm down!' David was a little embarrassed to be having this argument in front of a stranger. \\n\"\n"
        "                        \"\\n\"\n"
        "                        \"'I'm an angel, you said!' she carried on shouting.\\n\"\n"
        "                        \"\\n\"\n"
        "                        \"'MUST… FEED!' shouted the vampire furiously as he came even closer. He was determined to make a quick kill and get to bed as soon as possible, away from this terrible pair. \\n\"\n"
        "                        \"\\n\"\n"
        "                        \"His eyes opened wider and he showed his teeth. 'WHICH ... ONE?' \\n\"\n"
        "                        \"\\n\"\n"
        "                        \"'HER!' said David, pointing at his future wife. \\n\"\n"
        "                        \"\\n\"\n"
        "                        \"'HIM! HIM!' screamed Emma in rage. 'Please, take HIM!' \\n\"\n"
        "                        \"\\n\"\n"
        "                        \"The vampire approached David. \\n\"\n"
        "                        \"\\n\"\n"
        "                        \"'She's younger! Sweeter!' said David. \\n\"\n"
        "                        \"\\n\"\n"
        "                        \"The vampire turned to Emma. \\n\"\n"
        "                        \"\\n\"\n"
        "                        \"'He's bigger! There's more of him!' she said, pointing desperately. \\n\"\n"
        "                        \"\\n\"\n"
        "                        \"Suddenly a wave of tiredness came over the vampire. He was centuries old, and listening to them was exhausting and depressing. How could he feel better by feeding on either of these pathetic creatures? \\n\"\n"
        "                        \"\\n\"\n"
        "                        \"He looked down upon their terrified faces and cried, 'BAD BLOOD!' \\n\"\n"
        "                        \"\\n\"\n"
        "                        \"And with that, he disappeared into the night air and left Emma and David alone together. Together, as they had promised, for the rest of their lives.\\n\"\n"
        "                        \"\\n\"\n"
        "                        \" \\n\"\n"
        "                        \"\\n\"\n"
        "                        \"Story written by Clive Lane and adapted by Nicola Prentis.\";";
    return book;
};